apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 31009
  selector:
    name: mongo
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-deployment
spec:
  selector:
    matchLabels:
      name: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo              
        ports:
        - containerPort: 27017