apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 31009
  selector:
    name: mongo
